package com.xingguang.sinanya.system.imal;

public class HelpText {
    public static StringBuilder r = new StringBuilder()
            .append("r")
            .append("\t")
            .append("简化骰点")
            .append("\n")
            .append("用法：.r[表达式]")
            .append("\n")
            .append("示例：.r3d6/.r3d6k2/.r3#3d6k2/.rd/.r2d/.r2#d/.rd60/.r3+6")
            .append("\n")
            .append("r是最简单也是最复杂的骰点方式，常见的有以下几种使用方法:")
            .append("\n")
            .append("rd rd的意思.r1d100,也就是1-100的骰子投掷1次")
            .append("\n")
            .append("同理你也可以使用.r2d投掷.r2d100，或者.rd60投掷.r1d60,当然你也可以使用复杂的公式，比如.r3d6*5-2d/2+d60+7")
            .append("\n")
            .append("稍稍进阶一点的用法是k,意为取最大的几个结果，常用语dnd中，如.r3d6k2，就是骰3个1-6的骰子，取2个最大的结果")
            .append("\n")
            .append("此外也可以用#,譬如.r2#d,就是连续投2次1d100,常用语连续的检定")
            .append("\n")
            .append("值得注意的是，如果你没有加d字符，那么.r就是一个简单计算器，譬如.r3+6*5/2-7，就单纯是进行计算而非进行骰掷");

    public static StringBuilder rd = new StringBuilder()
            .append("rd")
            .append("\t")
            .append("骰点并进行简单计算")
            .append("\n")
            .append("用法：.r[表达式]")
            .append("\n")
            .append("示例：.r3d6/.r3d6k2/.r3#3d6k2/.rd/.r2d/.r2#d/.rd60")
            .append("\n")
            .append("是.r1d100的缩写，详情可以使用.man r查看.r命令的相关条目");

    public static StringBuilder rh = new StringBuilder()
            .append("rh")
            .append("\t")
            .append("进行暗骰")
            .append("\n")
            .append("用法:.rh[数值/技能/属性]")
            .append("\n")
            .append("示例：.ra50/.ra侦查/.rh力量+10/.rh")
            .append("\n")
            .append("当rh后未接其他参数，则为暗骰一枚默认骰，由骰娘私聊发送骰掷结果。当rh后接数值时，为一次暗骰rc数值检定，当录入人物卡后可在rh后接技能或属性。")
            .append("\n")
            .append("rh也可以使用.r命令的所有功能，详情可以参照.man r的回显");


    public static StringBuilder set = new StringBuilder()
            .append("set")
            .append("\t")
            .append("设置该群默认骰")
            .append("\n")
            .append("用法：.set [骰子面数]")
            .append("\n")
            .append("示例：.set20(设置该群默认骰为20面骰)")
            .append("\n")
            .append("未设置则默认骰为100面骰")
            .append("\n")
            .append("此设置是持久化的，所有塔骰系都可以读取到，无需重新设置。")
            .append("\n")
            .append("此设置是以群为单位的，不会影响你在别的群中的最大默认骰");


    public static StringBuilder ra = new StringBuilder()
            .append("ra")
            .append("\t")
            .append("技能检定，并计算成功等级(判定依据房规：1~5大成功，96~100大失败)")
            .append("\n")
            .append("用法：.ra [角色名:][属性/技能名][成功率]")
            .append("\n")
            .append("示例：.ra 力量 50 /.ra 侦查 60/.ra 缇娜:侦查")
            .append("\n")
            .append("当已经录入了人物卡数据后可省略成功率且进行简单计算。示例：.ra 力量/.ra 侦查+10/.ra侦查*2")
            .append("\n")
            .append("也可进行数值判定并加以简单计算。示例：.ra 50/.ra 50+10/.ra40*2+10")
            .append("\n")
            .append("需要注意的是，如果你当前已激活多人物卡，那么会强制调用你人物卡中的数据。譬如我当前人物卡的侦查是50，但我输入.ra 侦查 100后，会以50进行鉴定，而非100。你可以使用.ra 侦查+50来进行100的判定")
            .append("\n")
            .append("你也可以使用[角色名:技能]的方式对你其它角色卡的技能进行判定，这一般多用于kp带团中为多个npc的技能进行检定时。如[.ra 莱娜:斗殴]")
            .append("\n")
            .append("当你开启log功能，并已加入本群team后（相关命令可以查阅.man team和.man log），通过此命令+技能名进行检定成功，会自动记录到en记录器，在结团时可以使用.team en命令查看你正常游戏成功过的技能");


    public static StringBuilder rc = new StringBuilder()
            .append("rc")
            .append("\t")
            .append("技能检定，并计算成功等级(判定依据七版规则书限定：1大成功，若检定需要骰出的上限大于等于50，而骰出了100，那么大失败发生。若检定需要骰出的上限小于50，而骰出了96-100，那么大失败发生。)")
            .append("\n")
            .append("用法：.rc[角色名:][属性/技能名][成功率]")
            .append("\n")
            .append("示例：.rc 力量 50 /.rc 侦查 60/.ra 缇娜:侦查")
            .append("\n")
            .append("当已经录入了人物卡数据后可省略成功率且进行简单计算。示例：.rc 力量/.rc 侦查+10/.rc侦查*2")
            .append("\n")
            .append("也可进行数值判定并加以简单计算。示例：.rc 50/.rc50+10/.rc40*2+10")
            .append("\n")
            .append("来自规则书的例子：哈维有55%的图书馆使用技能。若他搜索图书馆寻找线索，守秘人可要求一个图书馆使用检定。由于他的技能是55%，因此只有骰出100时是大失败。若哈维在黑暗中偷偷搜索一所私人图书馆，仅有一支蜡烛照明，守秘人可将难度等级设为困难，要求骰出27以下。此时，哈维骰出96-100均为大失败。")
            .append("\n")
            .append("需要注意的是，如果你当前已激活多人物卡，那么会强制调用你人物卡中的数据。譬如我当前人物卡的侦查是50，但我输入.ra 侦查 100后，会以50进行鉴定，而非100。你可以使用.ra 侦查+50来进行100的判定")
            .append("\n")
            .append("你也可以使用[角色名:技能]的方式对你其它角色卡的技能进行判定，这一般多用于kp带团中为多个npc的技能进行检定时。如[.ra 莱娜:斗殴]");


    public static StringBuilder rb = new StringBuilder()
            .append("rb")
            .append("\t")
            .append("骰掷奖励骰并进行判定（可进行简单计算）（判定依据规则书：1为大成功。若检定需要骰出的上限大于等于50，而骰出了100，那么大失败发生；若检定需要骰出的上限小于50，而骰出了96-100，那么大失败发生。）")
            .append("\n")
            .append("用法：.rb[奖励骰个数] [角色名:][技能/属性/成功率]")
            .append("\n")
            .append("示例：.rb/.rb2 力量/.rb3 侦查+10/.rb 30*2+10/.rb3 缇娜:侦查")
            .append("\n")
            .append("在进行属性及技能判定前需要录入人物卡数据。当奖励骰个数为1时可将其置空。当需进行[技能/属性/成功率]判定时，在其与奖励骰个数之间添加一个（空格）。")
            .append("\n")
            .append("对每个奖励骰：在通常的一次百面骰之外，骰一个额外的十位骰。十位采用会给出较好的（一般来说是较小的）结果的那个十位骰。例如：进行奖励骰鉴定: D100=42[奖励骰:1] = 12。")
            .append("\n")
            .append("需要注意的是，如果你当前已激活多人物卡，那么会强制调用你人物卡中的数据。譬如我当前人物卡的侦查是50，但我输入.ra 侦查 100后，会以50进行鉴定，而非100。你可以使用.ra 侦查+50来进行100的判定")
            .append("\n")
            .append("你也可以使用[角色名:技能]的方式对你其它角色卡的技能进行判定，这一般多用于kp带团中为多个npc的技能进行检定时。如[.ra 莱娜:斗殴]")
            .append("\n")
            .append("当你开启log功能，并已加入本群team后（相关命令可以查阅.man team和.man log），通过此命令+技能名进行检定成功，会自动记录到en记录器，在结团时可以使用.team en命令查看你正常游戏成功过的技能");

    public static StringBuilder rp = new StringBuilder()
            .append("rp")
            .append("\t")
            .append("骰掷惩罚骰并进行判定（可进行简单计算）（判定依据规则书：1为大成功。若检定需要骰出的上限大于等于50，而骰出了100，那么大失败发生；若检定需要骰出的上限小于50，而骰出了96-100，那么大失败发生。）")
            .append("\n")
            .append("用法：.r[个数#]p[惩罚骰个数] [角色名:][技能/属性/成功率]")
            .append("\n")
            .append("示例：.rp/.rp2 力量/.rp3 侦查+10/.rp 30*2+10/.rp3 缇娜:侦查/.rp3# 手枪射击")
            .append("\n")
            .append("此外，在你进行譬如手枪射击检定时，你需要连续过2个或更多惩罚投，你可以使用#命令进行如下骰掷（这里假定手枪射击技能为60）")
            .append("\n")
            .append("用法：.rp[重复次数]#[惩罚投个数] [检定值]")
            .append("\n")
            .append("示例：.rp3#3 60")
            .append("\n")
            .append("在进行属性及技能判定前需要录入人物卡数据。当惩罚骰个数为1时可将其置空。当需进行[技能/属性/成功率]判定时，在其与惩罚骰个数之间添加一个（空格）。")
            .append("\n")
            .append("对每个惩罚骰：在通常的一次百面骰之外，骰一个额外的十位骰。十位采用会给出较坏的（一般来说是较大的）结果的那个十位骰。例如：进行惩罚骰鉴定: D100=42[惩罚骰:7] = 72。")
            .append("\n")
            .append("需要注意的是，如果你当前已激活多人物卡，那么会强制调用你人物卡中的数据。譬如我当前人物卡的侦查是50，但我输入.ra 侦查 100后，会以50进行鉴定，而非100。你可以使用.ra 侦查+50来进行100的判定")
            .append("\n")
            .append("你也可以使用[角色名:技能]的方式对你其它角色卡的技能进行判定，这一般多用于kp带团中为多个npc的技能进行检定时。如[.ra 莱娜:斗殴]");

    public static StringBuilder sc = new StringBuilder()
            .append("sc")
            .append("\t")
            .append("理智检定（判定依据规则书：1为大成功。若检定需要骰出的上限大于等于50，而骰出了100，那么大失败发生；若检定需要骰出的上限小于50，而骰出了96-100，那么大失败发生。")
            .append("\n")
            .append("用法：.sc[成功损失]/[失败损失] [当前理智值或目标人物卡]")
            .append("\n")
            .append("示例：.sc 0/1 50|.sc 1d6/1d10 60|.sc 1d2/1d6 缇娜")
            .append("\n")
            .append("也可用该指令进行回san。")
            .append("\n")
            .append("示例：.sc -1/-1d3 50 /.sc-1d6/-1d10 60/.sc -5/-5 60")
            .append("\n")
            .append("当录入人物卡信息以后，可以省去当前理智值，当调用当前人物卡以后，结果会更新到人物卡中。当已加入小队时，小队中的数据将实时更改")
            .append("\n")
            .append("你也可以使用.sc [表达式] [角色名]的方式对你其它角色卡进行理智检定，这一般多用于kp带团中为多个npc进行理智检定时（比如pc喊来的打手）。如[.sc 1d2/1d6 莱娜]")
            .append("\n")
            .append("当理智判定大失败后，自动失去最大值理智值。当检定大成功时，自动提示使用自救规则（由守秘人做最终决定）");

    public static StringBuilder hiy = new StringBuilder()
            .append("hiy")
            .append("\t")
            .append("获取骰点历史")
            .append("\n")
            .append("获取骰点历史，是你当前QQ号在所有群的骰点总历史概览。但只有ra和rc会被记录");


    public static StringBuilder ti = new StringBuilder()
            .append("ti")
            .append("\t")
            .append("临时疯狂症状。");

    public static StringBuilder li = new StringBuilder()
            .append("li")
            .append("\t")
            .append("总结疯狂症状。");

    public static StringBuilder en = new StringBuilder()
            .append("en")
            .append("\t")
            .append("技能/属性成长检定")
            .append("\n")
            .append("用法：.en[技能][成功率]")
            .append("\n")
            .append("示例：.en侦查50")
            .append("\n")
            .append("若调用人物卡数据则可省去后面的成功率，并结果自动更新到人物卡。")
            .append("\n")
            .append("若使用了奖励骰则不能获得技能成长。对于对抗检定，双方可能都实现某种程度的成功，但只有一方获胜，也只有胜者可以获得技能成长。");

    public static StringBuilder coc = new StringBuilder()
            .append("coc")
            .append("\t")
            .append("coc人物属性做成")
            .append("\n")
            .append("用法：.coc[6/7] [做成个数]")
            .append("\n")
            .append("示例：.coc6 5/.coc7 5")
            .append("\n")
            .append("当省去[6/7]时，人物做成默认为7版。")
            .append("\n")
            .append("coc6d/.coc7d    为详细人物做成，一次只能生成一张人物卡。");

    public static StringBuilder gas = new StringBuilder()
            .append("gas")
            .append("\t")
            .append("6版拓展规则煤气灯特征抽取。");


    public static StringBuilder tz = new StringBuilder()
            .append("tz")
            .append("\t")
            .append("非官方特质抽取。是朋友给的，不太建议使用，仅做娱乐项目和纪念意义");


    public static StringBuilder rav = new StringBuilder()
            .append("rav")
            .append("\t")
            .append("对抗骰点（房规）")
            .append("\n")
            .append("用法：.rav [角色名:][表达式]")
            .append("\n")
            .append("示例：.rav 力量/.rav 60/.rav 缇娜:侦查")
            .append("\n")
            .append("技能对抗（判定依据房规：1~5大成功，96~100大失败。）")
            .append("\n")
            .append("用法1:在群中使用，第一次使用被称为先手，第二次使用会成为后手。骰娘会自动给出对抗结论，采用对抗等级->投出点数->技能等级的顺序进行比较。")
            .append("\n")
            .append("用法2:当您已经在群中使用.kp进行kp身份设定后。可以私聊骰子.rav命令进行骰掷，视为在群中骰掷。骰掷技能和结果不会暴露给PL。")
            .append("\n")
            .append("你也可以使用[角色名:技能]的方式对你其它角色卡的技能进行判定，这一般多用于kp带团中为多个npc的技能进行检定时。如[.rav 莱娜:斗殴]")
            .append("\n")
            .append("使用格式可见于【.ra】指令。");

    public static StringBuilder rcv = new StringBuilder()
            .append("rcv")
            .append("\t")
            .append("对抗骰点（规则书）")
            .append("\n")
            .append("用法：.rcv [角色名:][表达式]")
            .append("\n")
            .append("示例：.rcv 力量/.rcv 60/.rcv 缇娜:侦查")
            .append("\n")
            .append("技能对抗（判定依据规则书：1为大成功。若检定需要骰出的上限大于等于50，而骰出了100，那么大失败发生；若检定需要骰出的上限小于50，而骰出了96-100，那么大失败发生。）")
            .append("\n")
            .append("用法1:在群中使用，第一次使用被称为先手，第二次使用会成为后手。骰娘会自动给出对抗结论，采用对抗等级->投出点数->技能等级的顺序进行比较。")
            .append("\n")
            .append("用法2:当您已经在群中使用.kp进行kp身份设定后。可以私聊骰子.rav命令进行骰掷，视为在群中骰掷。骰掷技能和结果不会暴露给PL。")
            .append("\n")
            .append("你也可以使用[角色名:技能]的方式对你其它角色卡的技能进行判定，这一般多用于kp带团中为多个npc的技能进行检定时。如[.rav 莱娜:斗殴]")
            .append("\n")
            .append("使用格式可见于【.rc】指令。");

    public static StringBuilder st = new StringBuilder()
            .append("st")
            .append("\t")
            .append("人物卡属性录入")
            .append("\n")
            .append("用法：.st[角色名]-[属性/技能][数值]")
            .append("\n")
            .append("示例：.st缇娜-力量50/.st缇娜-力量50体质60智力70..../.st力量50体质60智力70....")
            .append("\n")
            .append("st[角色名]")
            .append("\t")
            .append("切换当前人物卡到已录入[角色名]")
            .append("\n")
            .append("录入非标准技能名称则无法缓存也无法识别，且如未设置角色名则进入自定义模式，录入信息不保存到云端。所有塔系核心骰娘共用一个云数据库，同用一个人物卡档位，此设置跨群仍然有效。")
            .append("\n")
            .append("单纯使用.st角色名进行切换，注意team中的人物、检定时的数值同时也会因此变换")
            .append("\n")
            .append("注意：需在录入第一个技能或属性前添加-（减号，半角字符），你的人物名称不要携带-（减号，半角字符）字符")
            .append("\n")
            .append("此外有一个特殊事项，这里提供一个名为hpc的参数，用于在特殊规则下微调生命值上限，使用.st角色名-htc5或.stc htc5来实现");


    public static StringBuilder st_list = new StringBuilder()
            .append("st list")
            .append("\t")
            .append("查看已录入人物卡列表，分为当前角色和备选角色，会恒定存在一个自定义角色以供传统人物卡录入使用。你可以使用.man st命令查看如何录入多人物卡");

    public static StringBuilder st_rm = new StringBuilder()
            .append("st rm ")
            .append("\t")
            .append("删除人物卡")
            .append("\n")
            .append("用法：.st rm [角色名]")
            .append("\n")
            .append("示例：.st rm 缇娜")
            .append("\n")
            .append("不能删除当前选定人物卡，若此命令无回显则代表未找到此角色");

    public static StringBuilder st_clr = new StringBuilder()
            .append("st clr ")
            .append("\t")
            .append("清空数据")
            .append("\n")
            .append("用法：.st clr")
            .append("\n")
            .append("示例：.st clr")
            .append("\n")
            .append("尝试清空数据，如果已选择人物卡则不会删除，而是自动切换到自定义栏位，并重置自定义栏位。如果已经在自定义栏位，则直接重置数据");

    public static StringBuilder st_show = new StringBuilder()
            .append("st show")
            .append("\t")
            .append("显示当前人物卡属性及技能，此命令会有些刷屏，建议私聊使用");

    public static StringBuilder kp = new StringBuilder()
            .append("kp")
            .append("\t")
            .append("设置该群为带团群，并设置自己为本群kp")
            .append("\n")
            .append("配合team系列指令及rav/rcv指令，使用.man rav和.man rcv查看相应命令帮助");

    public static StringBuilder team_set = new StringBuilder()
            .append("team set")
            .append("\t")
            .append("添加群成员进入小队")
            .append("\n")
            .append("用法：.team set@[pl]")
            .append("\n")
            .append("示例：.team set@缇娜")
            .append("\n")
            .append("你可以一次添加多个成员，如.team set @缇娜 @安娜 @维娜")
            .append("\n")
            .append("你可以使用.man 查看team命令的具体用法");

    public static StringBuilder team = new StringBuilder()
            .append("team")
            .append("\t")
            .append("查看当前小队成员hp、san、db、体格等信息，此信息会随着人物卡信息变动而实时变动。")
            .append("\n")
            .append("此命令以群为单位，并且一个群同一时间仅可存在一个小队")
            .append("\n")
            .append("录入后，你可以使用多种小队管理命令，详情参见:\n")
            .append("man team rm")
            .append("\n")
            .append("man team clr")
            .append("\n")
            .append("man team call")
            .append("\n")
            .append("man team hp")
            .append("\n")
            .append("man team san")
            .append("\n")
            .append("man team desc")
            .append("\n")
            .append("man team en");

    public static StringBuilder team_desc = new StringBuilder()
            .append("team desc")
            .append("\t")
            .append("骰娘私聊kp小队成员人物卡属性");

    public static StringBuilder team_en = new StringBuilder()
            .append("team en")
            .append("\t")
            .append("统计小队内成员技能成功情况")
            .append("\n")
            .append("统计情况包括：一个角色从进入此队伍直到被移除出队伍，此段时间内ra技能/rc技能/rav技能/rcv技能判定成功。")
            .append("注意只有在log打开的情况下技能成功才会被记录，详情查看.man log");

    public static StringBuilder team_hp = new StringBuilder()
            .append("team hp")
            .append("\t")
            .append("增减小队成员hp")
            .append("\n")
            .append("用法：.team hp @[pl]（或all字符） [数值]")
            .append("\n")
            .append("示例：.team hp @缇娜 1/.team hp @缇娜 +5/.team hp @缇娜 @安娜 1d3/.team hp all 1d3")
            .append("\n")
            .append("当数值前不带符号时为减hp,当数值前为+时为回复hp。可以使用表达式，使用表达式时每个成员分别计算数值")
            .append("\n")
            .append("你可以使用all字符（不是at全体）代替at每一个成员的行为");

    public static StringBuilder team_san = new StringBuilder()
            .append("team san")
            .append("\t")
            .append("增减小队成员san值")
            .append("\n")
            .append("用法：.team san [pl] [pl]（或all字符） [SanCheck表达式]/.team san [pl] +[数值]")
            .append("\n")
            .append("示例：.team san @缇娜 @安娜 1/1d3/.team san @缇娜 +5/.team san all +5")
            .append("\n")
            .append("当数值前不带符号时为扣除san,当数值前为+时为回复san。可以使用表达式，使用表达式时每个成员分别计算数值")
            .append("\n")
            .append("你可以使用all字符（不是at全体）代替at每一个成员的行为");

    public static StringBuilder team_rm = new StringBuilder()
            .append("team rm")
            .append("\t")
            .append("删除小队成员")
            .append("\n")
            .append("用法：.team rm @[pl]")
            .append("\n")
            .append("示例：.team rm @缇娜");

    public static StringBuilder team_clr = new StringBuilder()
            .append("team clr")
            .append("\t")
            .append("清空小队");

    public static StringBuilder team_call = new StringBuilder()
            .append("team call")
            .append("\t")
            .append("自动at小队内所有成员");

    public static StringBuilder log_on = new StringBuilder()
            .append("log on")
            .append("\t")
            .append("开始记录跑团日志")
            .append("\n")
            .append("用法：.log on [日志名称]")
            .append("\n")
            .append("示例：.log on 毒汤")
            .append("\n")
            .append("注意，如果你开启的日志已经存在，则会在原基础上追加，而非清空后重新开启。同一个群同一时间只可以打开一个日志");

    public static StringBuilder log_off = new StringBuilder()
            .append("log off")
            .append("\t")
            .append("停止记录跑团日志")
            .append("\n")
            .append("用法：.log off [日志名称]")
            .append("\n")
            .append("示例：.log off 毒汤")
            .append("\n")
            .append("如果一个日志被关闭，则它可以被.log get [日志名称]。此外它还可以被.log on [日志名称]再次开启并追加");

    public static StringBuilder log_list = new StringBuilder()
            .append("log list")
            .append("\t")
            .append("查看当前群log列表 ");

    public static StringBuilder log_get = new StringBuilder()
            .append("log get")
            .append("\t")
            .append("获取日志文件")
            .append("\n")
            .append("用法：.log get [日志名称]")
            .append("\n")
            .append("示例：.log get 毒汤")
            .append("\n")
            .append("你会收到三个文件，分别是txt文件，docx染色文件和txt去括号文件。去括号文件会自动去除玩家使用()包裹的场外对话。你需要确保你当前QQ号的QQ邮箱可用");

    public static StringBuilder log_rm = new StringBuilder()
            .append("log rm")
            .append("\t")
            .append("删除记录")
            .append("\n")
            .append("用法：.log rm [日志名称]")
            .append("\n")
            .append("示例：.log rm 毒汤");

    public static StringBuilder ob = new StringBuilder()
            .append("ob")
            .append("\t")
            .append("进入旁观模式")
            .append("\n")
            .append("用法：\n.ob list\t查看当前旁观者列表\n.ob exit\t命令退出旁观列表\n.ob clr\t清空旁观列表")
            .append("\n")
            .append("加入ob列表后，你可以收到当前群内任何人的暗骰结果");

    public static StringBuilder ral = new StringBuilder()
            .append("ral")
            .append("\t")
            .append("多次数值检定（房规）")
            .append("\n")
            .append("用法：.ral [成功率] [判定次数]")
            .append("\n")
            .append("示例：.ral50 10")
            .append("\n")
            .append("如果次数太多，可能会暂时没有回复，请耐心等待");

    public static StringBuilder rcl = new StringBuilder()
            .append("rcl")
            .append("\t")
            .append("多次数值检定（规则书）")
            .append("\n")
            .append("用法：.rcl [成功率] [判定次数]")
            .append("\n")
            .append("示例：.rcl 50 10")
            .append("\n")
            .append("如果次数太多，可能会暂时没有回复，请耐心等待");

    public static StringBuilder clue = new StringBuilder()
            .append("clue")
            .append("\t")
            .append("添加线索")
            .append("\n")
            .append("用法：.clue [线索内容]")
            .append("\n")
            .append("示例：.clue 钥匙被埃德加拿走")
            .append("\n")
            .append("录入是没有任何回显的，你可以使用`.clue show`命令查看所有录入的内容。")
            .append("\n")
            .append("注意此命令仅仅是给玩家记录关键字用的，不要长篇录入");

    public static StringBuilder clue_show = new StringBuilder()
            .append("clue show")
            .append("\t")
            .append("显示当前群内记录线索集");

    public static StringBuilder clue_rm = new StringBuilder()
            .append("clue rm")
            .append("\t")
            .append("删除线索")
            .append("\n")
            .append("用法：.clue rm [线索时间戳]")
            .append("\n")
            .append("示例：.clue rm 2019-09-28 19:51:42")
            .append("\n")
            .append("你可以在.clue show回显中找到相关时间戳");

    public static StringBuilder clue_clr = new StringBuilder()
            .append("clue clr")
            .append("\t")
            .append("线索集清空");

    public static StringBuilder npc = new StringBuilder()
            .append("npc")
            .append("\t")
            .append("npc人物做成。当指令于群里使用，则外貌衣着部分发送到当前群，性格特长状态及属性私聊发送。此命令也可以私聊使用，则不会向群中发任何信息");

    public static StringBuilder dnd = new StringBuilder()
            .append("dnd")
            .append("\t")
            .append("dnd人物属性做成")
            .append("\n")
            .append("用法：.dnd [做成个数]")
            .append("\n")
            .append("示例：.dnd 5");

    public static StringBuilder ri = new StringBuilder()
            .append("ri")
            .append("\t")
            .append("先攻骰掷")
            .append("\n")
            .append("用法：.ri [调整值]（可选） [骰掷者名称]（可选）")
            .append("\n")
            .append("示例：.ri/.ri+4/.ri 4/.ri-4/.ri 4大雪主/.ri 地精1")
            .append("\n")
            .append("先攻骰掷，允许附加命令，譬如.ri+4等，如果在数字后面加入其它字符，将判定为你为什么东西骰先攻")
            .append("\n")
            .append("此命令不会有回显，使用.init命令查看先攻列表，使用.init clr命令清空先攻列表");

    public static StringBuilder init = new StringBuilder()
            .append("init")
            .append("\t")
            .append("查看当前先攻列表，需要使用.ri命令投先攻，详情查看.man ri")
            .append("\n")
            .append("init clr")
            .append("\t")
            .append("清空先攻列表");

    public static StringBuilder init_clr = new StringBuilder()
            .append("init clr")
            .append("\t")
            .append("清空先攻列表");

    public static StringBuilder init_rm = new StringBuilder()
            .append("init rm")
            .append("\t")
            .append("删除某条先攻骰掷记录")
            .append("\n")
            .append("用法：.init rm [用户名]")
            .append("\n")
            .append("示例：.init rm 老热望")
            .append("\n")
            .append("删除一条先攻骰掷记录，用于先攻骰掷操作失误，或此单位已死亡的情况下")
            .append("\n")
            .append("这个用户名是指，你输入.init后，于[]内的全部内容");

    public static StringBuilder init_set = new StringBuilder()
            .append("init set")
            .append("\t")
            .append("指定一条已有结果的先攻记录")
            .append("\n")
            .append("用法：.init set [用户名] [结果]")
            .append("\n")
            .append("示例：.init set 老热望 1")
            .append("\n")
            .append("指定一条已有结果的先攻记录，一般用于不小心清空了先攻记录，或某人不小心多骰了一次希望取第一次，可以用这条命令强制输入进去");

    public static StringBuilder magic = new StringBuilder()
            .append("magic")
            .append("\t")
            .append("dnd魔法速查")
            .append("\n")
            .append("用法：.magic5e [法术名]/.magic3r [法术名]")
            .append("\n")
            .append("示例：.magic5e 火球术/.magic3r 酸雾术")
            .append("\n")
            .append("如果你的法术名输入错误，那么会自动提示你可能的名称列表");

    public static StringBuilder con = new StringBuilder()
            .append("con")
            .append("\t")
            .append("dnd状态速查")
            .append("\n")
            .append("用法：.con [版本] [名称]")
            .append("\n")
            .append("示例：.con 5e 力竭/.con 3r 被吹动")
            .append("\n")
            .append("如果你的状态名输入错误，那么会自动提示你可能的状态名称列表");

    public static StringBuilder rule = new StringBuilder()
            .append("rule")
            .append("\t")
            .append("coc7版规则速查")
            .append("\n")
            .append("用法：.rule [规则名]")
            .append("\n")
            .append("示例：.rule 心理学")
            .append("\n")
            .append("如果你的名称输入错误，那么会自动提示你可能的规则名称列表");

    public static StringBuilder name = new StringBuilder()
            .append("name")
            .append("\t")
            .append("生成随机姓名")
            .append("\n")
            .append("用法：.name[数量]/.name [国籍]")
            .append("\n")
            .append("示例：.name 5/.name ch/.name en/.name jp");

    public static StringBuilder jrrp = new StringBuilder()
            .append("jrrp")
            .append("\t")
            .append("查看今日人品值")
            .append("\n");

    public static StringBuilder deck = new StringBuilder()
            .append("deck")
            .append("\t")
            .append("牌库抽取")
            .append("\n")
            .append("具体内容视骰娘搭载牌堆而定。使用【.deck help】查看骰娘当前装载的牌组及子命令");

    public static StringBuilder deck_help = new StringBuilder()
            .append("deck help")
            .append("\t")
            .append("牌库抽取帮助")
            .append("\n")
            .append("查看当前骰娘当前装载的牌组及子命令");

    public static StringBuilder getbook_card = new StringBuilder()
            .append("getbook card")
            .append("\t")
            .append("获取人物卡")
            .append("\n")
            .append("这是一张特制的人物卡，在第二页有给骰子使用的人物录入字符串（支持这个骰子的多人物卡）\n此外卡的自身素质也很强");

    public static StringBuilder getbook_make = new StringBuilder()
            .append("getbook make")
            .append("\t")
            .append("车卡指南")
            .append("\n")
            .append("这是一张基于.getbook card拿到的人物卡的车卡指南，适用于7版规则与1901规则书，写的非常详细，即使没读过规则书的人也通常不会出问题");

    public static StringBuilder getbook_kp = new StringBuilder()
            .append("getbook kp")
            .append("\t")
            .append("获取规则书")
            .append("\n")
            .append("获取一本1901规则书（PDF格式），我会在近期更新1907版本");

    public static StringBuilder getbook_rp = new StringBuilder()
            .append("getbook rp")
            .append("\t")
            .append("获取rp360问")
            .append("\n")
            .append("这是一个对rp很有帮助的提问集，不过只有问没有答。或许优秀的RP本就没有穷尽吧");

    public static StringBuilder w = new StringBuilder()
            .append("w")
            .append("\t")
            .append("无限骰点的简化命令")
            .append("\n")
            .append("用法：.w/.w[个数]/.w[个数]a[加骰线]/.w[个数]a[加骰线]k[成功线]/.w[个数]a[加骰线]k[成功线]+[调整值]")
            .append("\n")
            .append("示例：.w/.w10/.w10a5/.w10a5k2/.w10a5k2+5")
            .append("\n")
            .append("这是无限团的骰池的简化命令，不会输出骰点过程直接打印结果，骰掷次数不可以小于5");

    public static StringBuilder ww = new StringBuilder()
            .append("ww")
            .append("\t")
            .append("无限骰点的常规命令")
            .append("\n")
            .append("用法：.ww/.ww[个数N]/.ww[个数N]a[加骰线a]/.ww[个数N]a[加骰线a]k[成功线n]/.ww[个数N]a[加骰线a]k[成功线n]+[调整值b]/.ww[个数N]a[加骰线a]k[成功线n]m[面数m]+[调整值b]")
            .append("\n")
            .append("示例：.ww/.ww10/.ww10a5/.ww10a5k2/.ww10a5k2+5/.ww10a5k2m10+5")
            .append("\n")
            .append("这是无限团的骰池的常规命令。骰掷次数不可以小于5。\n")
            .append("当你的投掷次数在5-50之间时，会在群中输出详细信息。\n")
            .append("m面数不可以小于成功线n与加骰线a\n")
            .append("当你的投掷次数在51-300之间时，会在群中输出简略信息，并私聊你详细信息\n")
            .append("当你的投掷次数大于300时，只会在群中输出简略信息");

    public static StringBuilder ws = new StringBuilder()
            .append("ws")
            .append("\t")
            .append("无限骰点的统计命令")
            .append("\n")
            .append("用法：.ws/.w[个数]/.ws[个数]a[加骰线]/.ws[个数]a[加骰线]k[成功线]/.ws[个数]a[加骰线]k[成功线]+[调整值]")
            .append("\n")
            .append("示例：.ws/.ws10/.ws10a5/.ws10a5k2/.ws10a5k2+5")
            .append("\n")
            .append("这是无限团的骰池的统计命令，骰掷次数不可以小于5。只会在群中输出总览的简略信息");

    public static StringBuilder fate = new StringBuilder()
            .append("rf")
            .append("\t")
            .append("命运团的骰点命令")
            .append("\n")
            .append("用法：.rf")
            .append("\n")
            .append("示例：.rf")
            .append("\n")
            .append("这是命运团的骰点信息，命运团规定1、2为-，3、4为0，5、6为+（实际上是-1和+1），并重复骰掷4次，将结果相加");


    public static StringBuilder ban = new StringBuilder()
            .append("ban")
            .append("\t")
            .append("黑名单管理命令")
            .append("\n")
            .append("用法：.ban [rm] user/group/check [QQ号或群号] [缘由]")
            .append("\n")
            .append("示例：.ban user 123 测试封禁/.ban rm group 456")
            .append("\n")
            .append("这是骰子的云黑命令接口，你需要启用云黑选项并设置MasterQQ号才可以使用此命令")
            .append("\n")
            .append("ban后跟user或group，分别意为拉黑个人或群，再后面跟理由")
            .append("\n")
            .append("ban后跟rm再接user或group，意为删除黑名单。但注意，你只能删除自己添加的黑名单，由其他骰主添加的黑名单你无法删除，但命令会回复你谁添加的这个条目")
            .append("\n")
            .append("ban后跟check,可用于查询某人或某群的所有黑名单历史记录,后面不可再跟缘由");

    public static StringBuilder ban_list = new StringBuilder()
            .append("ban list")
            .append("\t")
            .append("黑名单查看命令")
            .append("\n")
            .append("用法：.ban user/group list")
            .append("\n")
            .append("示例：.ban user list 测试封禁/.ban group list")
            .append("\n")
            .append("查看当前生效的黑名单用户/群列表");

    public static StringBuilder white = new StringBuilder()
            .append("white")
            .append("\t")
            .append("白名单管理命令")
            .append("\n")
            .append("用法：.white [rm] user/group [QQ号或群号]")
            .append("\n")
            .append("示例：.white user 123/.white rm group 456")
            .append("\n")
            .append("这是骰子的白名单接口，但注意白名单虽然会上传到云服务器，但并不会被其他骰子调用，是你个人独有的。用法和.man ban中黑名单的用法类似");

    public static StringBuilder white_list = new StringBuilder()
            .append("white list")
            .append("\t")
            .append("白名单查看命令")
            .append("\n")
            .append("用法：.white user/group list")
            .append("\n")
            .append("示例：.white user list/.white group list")
            .append("\n")
            .append("查看当前生效的白名单用户/群列表");

    public static StringBuilder admin = new StringBuilder()
            .append("admin")
            .append("\t")
            .append("骰主管理器")
            .append("\n")
            .append("用法：.admin on/off/exit [群号]")
            .append("\n")
            .append("示例：.admin exit 1234567")
            .append("\n")
            .append("如果你已经设置了MasterQQ号，那么你可以通过私聊骰子这条命令，使其强制在某个群开/关/退出");

    public static StringBuilder dice_list = new StringBuilder()
            .append("dice list")
            .append("\t")
            .append("骰娘列表")
            .append("\n")
            .append("用法：.dice list")
            .append("\n")
            .append("示例：.dice list")
            .append("\n")
            .append("通过此命令，可以看到最近1小时内上报存活的骰娘列表（仅限塔系核心）");

    public static StringBuilder group = new StringBuilder()
            .append("group")
            .append("\t")
            .append("群管理命令")
            .append("\n")
            .append("用法：.group jrrp/npc/gas（等其他，详见下方说明） [0/1]")
            .append("\n")
            .append("示例：.group simple 1/.group jrrp 0")
            .append("\n")
            .append("群管理员可以关闭某个群中的骰子的特定功能，仅本群有效，0为关闭，1为开启，包含以下可选开关")
            .append("\n")
            .append("info")
            .append("\t")
            .append("查看当前所有开关的状态和本群的一些基本信息")
            .append("\n")
            .append("jrrp")
            .append("\t")
            .append("今日人品开关")
            .append("\n")
            .append("npc")
            .append("\t")
            .append("npc生成开关")
            .append("\n")
            .append("gas")
            .append("\t")
            .append("煤气灯特质获取开关")
            .append("\n")
            .append("bg")
            .append("\t")
            .append("人物背景信息获取开关")
            .append("\n")
            .append("tz")
            .append("\t")
            .append("玩家自定义特质获取开关")
            .append("\n")
            .append("welcome")
            .append("\t")
            .append("入群欢迎词获取开关")
            .append("\n")
            .append("simple")
            .append("\t")
            .append("简易模式获取开关，开启后会自动关闭譬如jrrp在内的很多开关，并强制关闭骰娘的所有自定义回复语，回归最简洁的样子")
            .append("\n")
            .append("ob")
            .append("\t")
            .append("旁观ob开关，加入ob可以接收到本群所有人的暗骰结果")
            .append("\n")
            .append("deck")
            .append("\t")
            .append("牌堆开关");

    public static StringBuilder welcome = new StringBuilder()
            .append("welcome")
            .append("\t")
            .append("入群欢迎词")
            .append("\n")
            .append("用法：.welcome [信息/open/close]")
            .append("\n")
            .append("示例：.welcome %s,你好/.welcome close/.welcome open")
            .append("\n")
            .append("入群欢迎词设置，你可以使用%s字符自动at新入群的成员")
            .append("\n")
            .append("welcome close和open可以在不影响已录入的入群词的前提下，开关welcome功能");

    public static StringBuilder group_list = new StringBuilder()
            .append("group list")
            .append("\t")
            .append("群检索命令")
            .append("\n")
            .append("用法：.group list")
            .append("\n")
            .append("示例：.group list")
            .append("\n")
            .append("群检索命令，可以查看骰子都加入了哪些群，每个群的群号、群名是什么，有多少人。此名命令仅私聊可用，此命令仅master可用");

    public static StringBuilder group_search = new StringBuilder()
            .append("group search")
            .append("\t")
            .append("群查询命令")
            .append("\n")
            .append("用法：.group search [群号]")
            .append("\n")
            .append("示例：.group search 162279609")
            .append("\n")
            .append("群查询命令，查询指定群的群名是什么，有多少人。此名命令仅私聊可用，此命令仅master可用");

    public static StringBuilder group_clean = new StringBuilder()
            .append("group clean")
            .append("\t")
            .append("群查询命令")
            .append("\n")
            .append("用法：.group clean")
            .append("\n")
            .append("示例：.group clean")
            .append("\n")
            .append("有时会出现记录的群数量与实际加入的数量不符，通过此命令将已不存在的群清理掉（可能是由于群解散之类）。此名命令仅私聊可用，此命令仅master可用");

    public static StringBuilder fire = new StringBuilder()
            .append("fire")
            .append("\t")
            .append("向火独行模块")
            .append("\n")
            .append("用法：.fire")
            .append("\n")
            .append("示例：.fire")
            .append("\n")
            .append("向火独行模块是一个将骰子作为守秘人，基于向火独行模组的特殊性制作的独立跑团模块。\n本模块主旨在于帮助刚入COC坑的新人更快的了解游戏过程、名词、玩法");

    public static StringBuilder cnmods = new StringBuilder()
            .append("cnmods")
            .append("\t")
            .append("魔都模组搜索模块")
            .append("\n")
            .append("用法：.cnmods [模组名] [页码]")
            .append("\n")
            .append("示例：.cnmods 向火独行/.cnmods 死 1/.cnmods 死 2")
            .append("\n")
            .append("魔都模组搜索模块直接接驳在魔都平台上，是受到魔都负责人授权后制作的模块，本模块只提供基于QQ平台的搜索功能，不提供上传/下载功能");

    public static StringBuilder nn = new StringBuilder()
            .append("nn")
            .append("\t")
            .append("取名改卡模块")
            .append("\n")
            .append("用法：.nn [名称]")
            .append("\n")
            .append("示例：.nn/.nn 莱娜")
            .append("\n")
            .append("自动取名模块，当你输入的名称存在时，则自动切换到人物卡。当你输入的名称不存在时，则自动切换到临时人物卡（所有临时人物卡互相覆盖数据）。当你没输入任何字符时，系统自动调用随机名字模块给你生成一个名字，并录入临时角色卡，同时因为和st指令关联，所以名字中不可带有-（减号，半角字符）字符");
}
